module.exports = [
  {
    username: "Victor",
    firstName: "Pia",
    lastName: "Yakubovics",
    email: "pyakubovics0@umn.edu",
    password: "123456789",
    dateOfBirth: "6/26/1991",
  },
  {
    username: "Juliett",
    firstName: "Ab",
    lastName: "Axel",
    email: "aaxel1@senate.gov",
    password: "123456789",
    dateOfBirth: "8/13/2001",
  },
  {
    username: "Papa1",
    firstName: "Nigel",
    lastName: "Cymper",
    email: "ncymper2@com.com",
    password: "123456789",
    dateOfBirth: "3/23/1995",
  },
  {
    username: "Quebec",
    firstName: "Peggi",
    lastName: "Aitkin",
    email: "paitkin3@quantcast.com",
    password: "123456789",
    dateOfBirth: "6/15/1990",
  },
  {
    username: "Bravo",
    firstName: "Luciana",
    lastName: "Dugmore",
    email: "ldugmore4@wp.com",
    password: "123456789",
    dateOfBirth: "10/19/1996",
  },
  {
    username: "Papa",
    firstName: "Stephie",
    lastName: "McIsaac",
    email: "smcisaac5@mysql.com",
    password: "123456789",
    dateOfBirth: "3/26/1990",
  },
  {
    username: "November",
    firstName: "Fairleigh",
    lastName: "MacPike",
    email: "fmacpike6@reference.com",
    password: "123456789",
    dateOfBirth: "8/3/1990",
  },
  {
    username: "Zulu",
    firstName: "Brod",
    lastName: "Thebeaud",
    email: "bthebeaud7@jiathis.com",
    password: "123456789",
    dateOfBirth: "7/26/2001",
  },
  {
    username: "Golf",
    firstName: "Talya",
    lastName: "Battie",
    email: "tbattie8@yandex.ru",
    password: "123456789",
    dateOfBirth: "4/2/2001",
  },
  {
    username: "Hotel",
    firstName: "Hillie",
    lastName: "Humphrys",
    email: "hhumphrys9@xrea.com",
    password: "123456789",
    dateOfBirth: "7/30/1990",
  },
];
